spring.application.name=automobile-catalog-service
server.port=8081

# PostgreSQL - Using Environment Variables
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA / Hibernate
spring.jpa.properties.hibernate.default_schema=ecom
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

# Razorpay
razorpay.key.id=${RAZORPAY_KEY_ID}
razorpay.key.secret=${RAZORPAY_KEY_SECRET}

# AWS S3
aws.s3.access-key=${AWS_ACCESS_KEY}
aws.s3.secret-key=${AWS_SECRET_KEY}
aws.s3.region=ap-south-1
aws.s3.bucket-name=autospares-images

# Elasticsearch
spring.elasticsearch.uris=${ELASTIC_URI:http://localhost:9200}

# Hikari Connection Pool
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1

spring.main.lazy-initialization=true

spring.devtools.add-properties=false
management.endpoints.enabled-by-default=false

server.tomcat.threads.max=10
server.tomcat.threads.min-spare=2